[package]
name = "document-worker"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
document-engine-mock = { path = "../../crates/document-engine-mock" }
document-engine-api = { path = "../../crates/document-engine-api" }

[lints]
workspace = true
