[package]
name = "desktop"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
document-engine-mock = { path = "../../crates/document-engine-mock" }
document-protocol = { path = "../../crates/document-protocol" }
document-session = { path = "../../crates/document-session" }

[lints]
workspace = true
